#!/usr/bin/env python3
"""tools/update-compat-log.py -- regenerate docs/compat-log.md's own
COUNTER section from its LOGS section, and flag any issue-id used in
LOGS that doesn't match one of compat-scan's own checks.

    python3 tools/update-compat-log.py

Dev-only tooling (unlike compat-scan itself): this never needs to run
on vaporOS, only ever on whoever's updating the log after porting
something new. Plain Python for that reason -- no need for the
C/portable-to-the-device duality compat-scan's own file has.

Never hand-edit the COUNTER section in docs/compat-log.md -- it's
fully regenerated by this script every run; only LOGS is hand-written.
"""

import re
import sys
from pathlib import Path
from collections import OrderedDict

REPO_ROOT = Path(__file__).resolve().parent.parent
LOG_PATH = REPO_ROOT / "docs" / "compat-log.md"
COMPAT_SCAN_PATH = REPO_ROOT / "compat-scan" / "compat_scan_main.c"

COUNTER_MARKER = "---- COUNTER "
LOGS_MARKER = "---- LOGS "

# A new entry starts at the left margin: "(N) issue-id -- note...".
# Anything else (blank, "[program]", or an indented continuation line)
# is not a new entry.
ENTRY_RE = re.compile(r"^\((\d+)\)\s+([\w-]+)\s+--")
CHECK_ID_RE = re.compile(r'^\s*"([\w-]+)",\s*SEV_')


def parse_log_entries(text):
    """Returns an OrderedDict of issue-id -> total count, in first-seen
    order (so ties in the final sort stay in a stable, readable order).
    """
    counts = OrderedDict()
    in_logs = False

    for line in text.splitlines():
        if line.startswith(LOGS_MARKER):
            in_logs = True
            continue

        if not in_logs:
            continue

        match = ENTRY_RE.match(line)
        if match:
            count = int(match.group(1))
            issue_id = match.group(2)
            counts[issue_id] = counts.get(issue_id, 0) + count

    return counts


def parse_known_check_ids(compat_scan_source):
    ids = []
    for line in compat_scan_source.splitlines():
        match = CHECK_ID_RE.match(line)
        if match:
            ids.append(match.group(1))
    return ids


def format_counter_section(counts):
    if not counts:
        return ["(no entries logged yet)"]

    # Sort by count descending; ties keep their first-seen order from
    # the LOGS section (stable sort), so the most zero-effort-to-fix
    # or most-common problems surface first without the order jumping
    # around from run to run for equal counts.
    ordered = sorted(counts.items(), key=lambda kv: -kv[1])
    max_id_len = max(len(issue_id) for issue_id, _ in ordered)

    lines = []
    for issue_id, count in ordered:
        padded_id = issue_id.ljust(max_id_len)
        lines.append(f"{padded_id} = {count}")
    return lines


def rebuild_file(text, counter_lines):
    lines = text.splitlines(keepends=True)
    counter_idx = next(
        i for i, line in enumerate(lines) if line.startswith(COUNTER_MARKER)
    )
    logs_idx = next(
        i for i, line in enumerate(lines) if line.startswith(LOGS_MARKER)
    )

    new_lines = (
        lines[: counter_idx + 1]
        + [line + "\n" for line in counter_lines]
        + ["\n"]
        + lines[logs_idx:]
    )
    return "".join(new_lines)


def main():
    if not LOG_PATH.exists():
        print(f"error: {LOG_PATH} does not exist", file=sys.stderr)
        sys.exit(1)

    if not COMPAT_SCAN_PATH.exists():
        print(f"error: {COMPAT_SCAN_PATH} does not exist", file=sys.stderr)
        sys.exit(1)

    log_text = LOG_PATH.read_text()
    compat_scan_source = COMPAT_SCAN_PATH.read_text()

    counts = parse_log_entries(log_text)
    known_ids = set(parse_known_check_ids(compat_scan_source))

    counter_lines = format_counter_section(counts)
    new_text = rebuild_file(log_text, counter_lines)
    LOG_PATH.write_text(new_text)

    print(f"Generated counter in {LOG_PATH} ({len(counts)} issue-id(s)).")

    not_automated = sorted(set(counts) - known_ids)
    if not_automated:
        print(
            "\nLogged but not yet a compat-scan check -- candidates for a "
            "new check:"
        )
        for issue_id in not_automated:
            print(f"  {issue_id} (logged {counts[issue_id]} time(s))")
    else:
        print("\nEvery logged issue-id already has a matching compat-scan check.")


if __name__ == "__main__":
    main()
